# - Try to find LibXML
# Once done this will define
#
#  LIBXML_FOUND - system has LibXML
#  LIBXML_INCLUDE_DIRS - the LibXML include directory
#  LIBXML_LIBRARIES - Link these to use LibXML
#  LIBXML_VERSION - SO version of the found libxml library
#
#  This CMake file generated by Wayne Brassem <wbrassem@juniper.net>
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#
#  1. Redistributions of source code must retain the copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. The name of the author may not be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
#  IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
#  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
#  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#  NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
#  THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
include(FindPackageHandleStandardArgs)

if(LIBXML_LIBRARIES AND LIBXML_INCLUDE_DIRS)
    # in cache already
    set(LIBXML_FOUND TRUE)
else()
    find_path(LIBXML_INCLUDE_DIR
        NAMES
        libxml/xpath.h
        libxml/tree.h
        PATHS
        /usr/include
        /usr/local/include
        /opt/local/include
        /sw/include
        ${CMAKE_INCLUDE_PATH}
        ${CMAKE_INSTALL_PREFIX}/include
    )

    find_library(LIBXML_LIBRARY
        NAMES
        xml
        xml2
        libxml
        libxml2
        PATHS
        /usr/lib
        /usr/lib64
        /usr/local/lib
        /usr/local/lib64
        /opt/local/lib
        /sw/lib
        ${CMAKE_LIBRARY_PATH}
        ${CMAKE_INSTALL_PREFIX}/lib
    )

    set(LIBXML_INCLUDE_DIRS ${LIBXML_INCLUDE_DIR})
    set(LIBXML_LIBRARIES ${LIBXML_LIBRARY})
    mark_as_advanced(LIBXML_INCLUDE_DIRS LIBXML_LIBRARIES)

    # handle the QUIETLY and REQUIRED arguments and set LIBXML_FOUND to TRUE
    # if all listed variables are TRUE
    find_package_handle_standard_args(LibXML FOUND_VAR LIBXML_FOUND
        REQUIRED_VARS LIBXML_LIBRARY LIBXML_INCLUDE_DIR
        VERSION_VAR LIBXML_VERSION)
endif()
